# Generated by Django 4.2.5 on 2023-09-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chat_id', models.UUIDField()),
                ('author_id', models.UUIDField()),
            ],
        ),
    ]
