# Generated by Django 4.2.5 on 2023-09-05 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_created_at_message_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 15, 52, 46, 105745)),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
