# Generated by Django 4.2.5 on 2023-09-05 21:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_created_at_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 15, 57, 50, 298585)),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4a577c4-fcbf-48bf-8b02-5ad41f881f95'), primary_key=True, serialize=False),
        ),
    ]
